name = "tabby-csv-updater"
main = "api/update-csv.js"
compatibility_date = "2023-10-30"

[env.production]
vars = { ENVIRONMENT = "production" }

# GitHub token will be set as a secret in Cloudflare Workers dashboard
# wrangler secret put GITHUB_TOKEN
